#!/usr/bin/env python3
"""Build provenance-preserving grant draft packets from reviewed opportunity registries."""

from __future__ import annotations

import argparse
import json
import re
from datetime import date, datetime, timezone
from pathlib import Path


def parse_date(value: str | None) -> date | None:
    if not value:
        return None
    try:
        return date.fromisoformat(value[:10])
    except ValueError:
        return None


def slug(value: str) -> str:
    return re.sub(r"[^a-z0-9._-]+", "-", value.lower()).strip("-")


def days_old(value: str | None, today: date) -> int | None:
    parsed = parse_date(value)
    return None if parsed is None else (today - parsed).days


def eligible(grant: dict, registry: dict, cfg: dict, today: date) -> tuple[bool, list[str]]:
    reasons: list[str] = []
    review = grant.get("lastVerified") or registry.get("updated")
    age = days_old(review, today)

    if age is None:
        reasons.append("missing/invalid source review date")
    elif age > int(cfg["freshnessDays"]):
        reasons.append(f"source review is {age} days old")

    due = parse_date(grant.get("nextDue"))
    if due and due < today:
        reasons.append("deadline has passed")

    if grant.get("draftHold") is True:
        reasons.append("explicit draft hold")

    if grant.get("status") not in set(cfg["allowedStatuses"]):
        reasons.append(f"status {grant.get('status')} is not draft-enabled")

    if int(grant.get("fitScore", -1)) < int(cfg["draftThreshold"]):
        reasons.append(f"fit score below {cfg['draftThreshold']}")

    if not grant.get("source"):
        reasons.append("missing authoritative source")

    if not grant.get("applicantRoute") or not grant.get("directEligibility"):
        reasons.append("applicant route unresolved")

    return (not reasons, reasons)


def render(project: str, grant: dict, registry: dict, today: date) -> str:
    gates = "\n".join(f"- [ ] {item}" for item in grant.get("gates", []))
    policy = "\n".join(f"- {item}" for item in grant.get("policyNotes", [])) or "- None recorded."
    blockers = "\n".join(f"- [ ] {item}" for item in grant.get("currentBlockers", [])) or "- [ ] Reconcile mechanism-specific blockers with the current source."
    due = grant.get("nextDue") or "Rolling / not currently specified"
    verified = grant.get("lastVerified") or registry.get("updated") or "unknown"
    return f"""<!-- AUTOGENERATED GRANT DRAFT. Rebuild from source registry; do not hand-edit this file. -->

# {grant["title"]}

**Project:** {project}  
**Sponsor:** {grant["sponsor"]}  
**Mechanism:** {grant["mechanism"]}  
**Strategic fit:** {grant["fitScore"]}/100  
**Application route:** {grant["applicantRoute"]}  
**Deadline:** {due}  
**Source verified:** {verified}  
**Draft generated:** {today.isoformat()}  
**Authoritative source:** {grant["source"]}

## Drafting status

This is a pre-submission drafting packet generated only after the opportunity passed the portfolio freshness, timing, fit, and applicant-route gates. It is not evidence that the project is eligible, that the sponsor will accept the application, or that unresolved partner and institutional requirements have been satisfied.

## Working project summary

{registry.get("thesis", project)}

For this mechanism, the working case is:

{grant["rationale"]}

## Eligibility and applicant structure

{grant["directEligibility"]}

Before narrative language is promoted into a submission, confirm the legal applicant, principal investigator or project lead, institutional registrations, partner roles, and any mechanism-specific restrictions against the current sponsor instructions.

## Specific aims / objectives scaffold

1. Define the measurable access, navigation, implementation, or service-delivery problem addressed by the proposed work.
2. Implement the bounded technical or programmatic intervention described in the source repository without expanding claims beyond the existing evidence base.
3. Evaluate feasibility, access, referral quality, implementation outcomes, and other mechanism-appropriate endpoints using a prespecified analysis plan.

> Drafting rule: replace this scaffold with mechanism-specific aims only after the sponsor instructions and project evidence manifest are reconciled.

## Significance / need

Use the source repository literature matrix and evidence package to establish the problem, affected population, access gap, current workflow failure, and why the proposed intervention belongs within this sponsor's mission. Every quantitative claim should resolve to a verified citation or project dataset.

## Innovation

Describe only defensible innovation already represented in the source repository. Separate technical novelty, implementation novelty, workflow novelty, and research contribution. Do not use routine software development as the primary innovation claim.

## Approach

### Work package 1 — source and workflow definition
- Lock the implementation setting, population, referral origin, and authoritative source boundaries.
- Confirm data classes and minimum necessary information.

### Work package 2 — implementation
- Deliver the grant-bounded functionality.
- Preserve source provenance, freshness controls, safety constraints, and failure-state behavior.

### Work package 3 — evaluation
- Define primary and secondary outcomes before analysis.
- Capture implementation and access outcomes rather than vanity engagement metrics.
- Preserve an auditable analysis path into manuscript-ready tables and figures.

### Work package 4 — dissemination and sustainment
- Produce sponsor reporting artifacts.
- Route validated results into the manuscript preparation pipeline.
- Define post-award sustainment, procurement, commercialization, or public-benefit continuation as appropriate.

## Required gates

{gates}

## Current blockers

{blockers}

## Budget frame

**Current registry value:** {grant["budget"]}  
**Duration:** {grant["duration"]}

Translate this into personnel, implementation, partner/subaward, evaluation, infrastructure, dissemination, and indirect-cost lines only after current sponsor rules are verified.

## Human subjects / clinical-trial boundary

**Registry classification:** {grant["clinicalTrial"]}

Do not infer exemption, institutional review requirements, or clinical-trial status from this generated packet. Reconcile the current protocol and sponsor definitions before submission.

## Policy and mechanism notes

{policy}

## Evidence-to-manuscript handoff

The proposal should reuse the same evidence controls as a publishable manuscript:

- source registry with retrieval/review dates;
- citation verification log;
- explicit analysis protocol;
- data provenance;
- prespecified outcomes;
- limitations and claim boundaries;
- reproducible tables/figures;
- change/audit trail connecting proposal claims to eventual results.

If funded, create a project-specific manuscript branch at award activation rather than reconstructing methods retrospectively.

## Final pre-submission controls

- [ ] Re-open the authoritative opportunity page.
- [ ] Confirm the opportunity remains active.
- [ ] Confirm deadline/time zone and submission portal.
- [ ] Confirm applicant eligibility and registrations.
- [ ] Confirm current forms, page limits, review criteria, and attachments.
- [ ] Reconcile aims, milestones, budget, evaluation endpoints, and partner letters.
- [ ] Replace every unresolved placeholder or scaffold statement.
- [ ] Run citation, privacy, statistical, and claim-boundary review.
"""


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--config", default="grants/pipeline-config.json")
    parser.add_argument("--registry", action="append", default=[], help="project=path")
    parser.add_argument("--output", default="grants/generated")
    args = parser.parse_args()

    cfg = json.loads(Path(args.config).read_text())
    today = datetime.now(timezone.utc).date()
    out_root = Path(args.output)
    out_root.mkdir(parents=True, exist_ok=True)

    index = {
        "schemaVersion": "grant-draft-index.v1",
        "generatedAt": datetime.now(timezone.utc).isoformat(),
        "draftThreshold": cfg["draftThreshold"],
        "freshnessDays": cfg["freshnessDays"],
        "drafts": [],
        "held": [],
    }

    for item in args.registry:
        project, path = item.split("=", 1)
        registry = json.loads(Path(path).read_text())
        reg_age = days_old(registry.get("updated"), today)
        if reg_age is None or reg_age > int(cfg["freshnessDays"]):
            raise SystemExit(f"{project}: registry is missing a current review date")

        project_dir = out_root / slug(project)
        project_dir.mkdir(parents=True, exist_ok=True)

        for grant in registry.get("opportunities", []):
            ok, reasons = eligible(grant, registry, cfg, today)
            record = {
                "project": project,
                "id": grant.get("id"),
                "title": grant.get("title"),
                "fitScore": grant.get("fitScore"),
                "status": grant.get("status"),
                "source": grant.get("source"),
                "nextDue": grant.get("nextDue"),
            }
            if not ok:
                record["reasons"] = reasons
                index["held"].append(record)
                continue

            target = project_dir / f"{slug(grant['id'])}.md"
            target.write_text(render(project, grant, registry, today), encoding="utf-8")
            record["path"] = str(target)
            index["drafts"].append(record)

    (out_root / "index.json").write_text(json.dumps(index, indent=2) + "\n", encoding="utf-8")
    print(json.dumps(index, indent=2))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
